export const state = {
    gameScale: 1,
    rangeScale: 1,
    EARTH_RADIUS: 60,
    ORBIT_PATHS: [],
    orbitLockStates: [false, true, true],
    orbitSlotCapacities: [4, 4, 4],
    orbitUpgradesCount: [0, 0, 0],
    shieldUpgradeLevel: 0,
    orbitRotations: [0, 0, 0],
    earthRotation: 0,
    planetName: "EARTH",
    activeThemeKey: "oasis",
    lastInputTime: 0,
    waveActive: false,
    spawnQueue: [],
    spawnTimer: 0,
    lightningArcsToDraw: [],
    shipAttackBeamsToDraw: [],
    audioCtx: null,
    isSfxEnabled: true,
    isBgmEnabled: true,
    sfxVolume: 1.0,
    bgmVolume: 1.0,
    bgmAudio: null,
    activeBgmKey: 'default',
    bgmUnlockListenerBound: false,
    isScanlinesEnabled: true,
    screenShakeIntensity: 1.0,
    isDevMode: false,
    deferredInstallPrompt: null,
    gameNoticeTimer: null,
    tutorialHints: { planet: false, build: false },
    planetTutorialTooltipShown: false,
    starterTooltipsSuppressed: false,
    firstDeploymentSlotHintShown: false,
    masterCommandTourSeen: false,
    masterCommandTourStep: 0,
    modeTransitionActive: false,
    gameLoopStarted: false,
    cosmicData: 0,
    research: { startSlots: 0, baseShield: 0, baseDamage: 0 },
    game: {
        running: false, paused: false, score: 0, gold: 500, wave: 1, nextWaveTimer: 0,
        earthMaxHealth: 200, earthHealth: 200, earthMaxShield: 100, earthShield: 100, towersBuiltCount: 0,
        totalWaveEnemies: 10, enemiesSpawnedThisWave: 0,
        selectedShopType: null, selectedTower: null, selectedOrbitIndex: null,
        mousePos: { x: 0, y: 0 }, hoveredOrbit: null, hoveredOrbitIndex: null, hoveredAngle: 0,
        towers: [], enemies: [], projectiles: [], particles: [], orbitGridHighlights: false,
        mode: 'defense',
        commandDirectives: {},
        directiveKills: 0,
        hazard: null, fastForward: false, cameraShake: 0, damageOverlayAlpha: 0, shieldOverlayAlpha: 0,
        tactical: { laser: { cd: 0, maxCd: 1800, active: false, unlocked: false }, emp: { cd: 0, maxCd: 2400, unlocked: false }, overcharge: { cd: 0, maxCd: 3600, activeTime: 0, unlocked: false } },
        bossIndex: 0,
        bossRepairKits: 0
    },
    bossMode: {
        active: false, phase: 'idle', wave: 0, frame: 0, spawnTimer: 0, spawned: 0, requiredKills: 0, kills: 0,
        player: { x: 0, y: 0, hp: 100, maxHp: 100, fireCooldown: 0, dragging: false, dragOffsetX: 0, dragOffsetY: 0, targetX: 0, targetY: 0, weapon: 'default', repairKits: 0, dashCooldown: 0, isDashing: false, dashTimer: 0 },
        enemies: [], projectiles: [], enemyProjectiles: [], boss: null, rewardOptions: [], victoryTimer: 0, defeatedBossName: '', drops: []
    },
    resizeRaf: null,
    pendingAppUpdate: false,
    swRegistration: null,
    
    // Function hooks to prevent circular dependencies
    playSynthSound: () => {},
    shakeScreen: () => {},
    createExplosion: () => {},
    getDirectiveEffectValue: () => null,
    spawnReward: () => {},
    updateStatsUI: () => {},
    canvas: null,
    ctx: null
};
